// Catalogue temporaire, destiné à être remplacé par le futur i18n global.
export const PRODUCT_PAGE_TEXT = {
  backToScan: 'Retour au scan',
  openProductPage: 'Ouvrir la page produit',
  refresh: 'Actualiser les informations',
  loading: 'Chargement en cours…',
  readonlyNotice: 'Réglages affichés en lecture seule.',
  commandsUnavailable:
    'Les commandes seront disponibles dans un prochain lot.',
  openCommand: {
    cancel: 'Annuler',
    awaitingConfirmation: 'Confirmation requise',
    executing: 'Commande en cours…',
    unavailable: 'Commande indisponible',
    disconnected: 'Périphérique déconnecté',
    stale: 'Résultat obsolète',
    failed: 'Échec de la commande',
    alreadyInProgress: 'Une commande est déjà en cours',
    cancelled: 'Commande annulée',
  },
  widoorCommands: {
    warning:
      'Un mouvement réel du moteur sera déclenché après confirmation.',
    physicalValidationRequired: 'Validation physique requise',
    protected: 'Fonction protégée — prochain lot',
    open: {
      label: 'Ouvrir',
      confirmTitle: 'Ouvrir la porte ?',
      confirmMessage:
        'Cette action déclenche un mouvement réel du moteur. Vérifiez que ' +
        'la zone est dégagée et que l’arrêt physique est accessible.',
      confirmAction: 'Ouvrir',
      confirmed: 'Ouverture confirmée',
      notConfirmed: 'Commande envoyée, mais ouverture non confirmée',
    },
    close: {
      label: 'Fermer',
      confirmTitle: 'Fermer la porte ?',
      confirmMessage:
        'Cette action déclenche un mouvement réel du moteur. Vérifiez que ' +
        'la zone est dégagée et que l’arrêt physique est accessible.',
      confirmAction: 'Fermer',
      confirmed: 'Fermeture confirmée',
      notConfirmed: 'Commande envoyée, mais fermeture non confirmée',
    },
    openShortTimed: {
      label: 'Ouverture temporisée courte',
      confirmTitle: '',
      confirmMessage: '',
      confirmAction: '',
      confirmed: '',
      notConfirmed: '',
    },
    openLongTimed: {
      label: 'Ouverture temporisée longue',
      confirmTitle: '',
      confirmMessage: '',
      confirmAction: '',
      confirmed: '',
      notConfirmed: '',
    },
    learning: {
      label: 'Apprentissage',
      confirmTitle: '',
      confirmMessage: '',
      confirmAction: '',
      confirmed: '',
      notConfirmed: '',
    },
  },
  sections: {
    commands: 'Commandes',
    settings: 'Réglages',
    information: 'Informations',
    userSettings: 'Réglages utilisateur',
    professionalSettings: 'Réglages professionnels',
    identity: 'Produit connecté',
    version: 'Versions et identification',
    dates: 'Dates et cycles',
    maintenance: 'Maintenance',
    motorState: 'État moteur',
  },
  states: {
    available: 'Disponible',
    unavailable: 'Non disponible',
    invalid: 'Donnée invalide',
    notLoaded: 'Non chargée',
    failed: 'Lecture impossible',
    disconnected: 'Déconnecté',
    stale: 'Données obsolètes',
    connected: 'Connecté',
    invalidProfile: 'Profil incohérent',
    partialSuccess: 'Succès partiel',
    success: 'Informations disponibles',
    cancelled: 'Lecture annulée',
  },
  profile: 'Profil',
  productName: 'Nom produit',
  displayedName: 'Nom affiché',
  room: 'Pièce',
  deviceId: 'Identifiant du périphérique',
  connection: 'Connexion',
  lastRefresh: 'Dernière actualisation',
  noRoom: 'Non renseignée',
  noValue: 'Non disponible',
  noMotorState: 'Aucun état moteur reçu',
  yes: 'Oui',
  no: 'Non',
  notInitialized: 'Non initialisée',
  invalidHistoricalDate: 'Date historique invalide',
  historicalFad: 'FAD historique brut',
  historicalFadNotice: 'Signification métier non confirmée',
  rawFrame: 'Trame brute',
  technicalDetails: 'Détails techniques',
  serviceUuid: 'Service UUID',
  characteristicUuid: 'Caractéristique UUID',
  errorCode: 'Code d’erreur',
  errors: {
    serviceAbsent: 'Service BLE non disponible',
    characteristicAbsent: 'Non disponible sur ce firmware',
    notReadable: 'Lecture non prise en charge',
    unknown: 'Une erreur est survenue pendant la lecture.',
  },
  errorDetails: {
    serviceAbsent:
      'Le service BLE nécessaire n’est pas exposé par ce produit.',
    characteristicAbsent:
      'La caractéristique BLE nécessaire n’est pas exposée par ce produit.',
    notReadable:
      'La caractéristique BLE ne permet pas la lecture sur ce produit.',
  },
  version: {
    motor: 'Logiciel moteur',
    ble: 'Logiciel Bluetooth',
    stack: 'Stack BLE',
    productType: 'Type produit brut',
    productSubtype: 'Sous-type',
    crc: 'CRC',
    motorAddress: 'Adresse moteur',
  },
  dates: {
    firstCommissioning: 'Première mise en service',
    lastMaintenance: 'Dernière maintenance',
    totalCycles: 'Total cycles',
    cyclesSinceMaintenance: 'Cycles depuis maintenance',
  },
  maintenance: {
    initializationCount: 'Initialisations',
    cyclesSinceInitialization: 'Cycles depuis initialisation',
    obstacleDetectionCount: 'Détections obstacle',
    wrongStopOpenCount: 'Mauvais arrêts ouverture',
    wrongStopCloseCount: 'Mauvais arrêts fermeture',
    learningCycleCount: 'Cycles d’apprentissage',
    encoderErrorCount: 'Erreurs encodeur',
    motorErrorCount: 'Erreurs moteur',
  },
  user: {
    lockMode: 'Mode de condamnation',
    lockModeRaw: 'Mode de condamnation brut',
    openSpeed: 'Vitesse d’ouverture',
    closeSpeed: 'Vitesse de fermeture',
    shortTiming: 'Temporisation courte',
    longTiming: 'Temporisation longue',
    staticLight: 'Éclairage statique',
    dynamicLight: 'Éclairage dynamique',
    rgb: 'Indicateur RGB',
    peripheralByte1: 'Octet périphériques utilisateur 1',
    peripheralByte2: 'Octet périphériques utilisateur 2',
  },
  professional: {
    weightRange: 'Plage de poids',
    exactWeight: 'Poids exact',
    breakForceAtOpen: 'Force/freinage à l’ouverture',
    nearOpenSpeed: 'Vitesse de fin d’ouverture',
    nearCloseSpeed: 'Vitesse de fin de fermeture',
    nearOpenTorque: 'Couple fin ouverture',
    nearCloseTorque: 'Couple fin fermeture',
    brakingOpenPower: 'Freinage ouverture',
    obstacleSensitivity: 'Sensibilité obstacle',
    nearOpenProportional: 'Proportionnelle ouverture',
    nearCloseProportional: 'Proportionnelle fermeture',
    nearOpenIntegral: 'Intégrale ouverture',
    nearCloseIntegral: 'Intégrale fermeture',
    peripherals:
      'Périphériques bruts (entrées, verrou et tests radar)',
    peripheralsWithoutLock:
      'Périphériques bruts (entrées et tests radar)',
  },
  motor: {
    rawState: 'État brut',
    stateLabel: 'État technique',
    currentPosition: 'Position courante',
    maximumPosition: 'Position maximale',
    percentage: 'Ouverture',
    error: 'Erreur',
    switchesRaw: 'Bits d’état bruts',
    pushAndGo: 'Push & Go',
    ble: 'BLE',
    automaticManual: 'Auto/Manuel',
    direction: 'Direction',
    pairing: 'Appairage',
    openingStarted: 'Début ouverture',
    stoppedAfterOpening: 'Arrêt après ouverture',
    closingStarted: 'Début fermeture',
    stoppedAfterClosing: 'Arrêt après fermeture',
    unknown: 'État non documenté',
  },
} as const;
