// Catalogue temporaire, destiné à être remplacé par le futur i18n global.
export const PRODUCT_PAGE_TEXT = {
  backToScan: 'Retour au scan',
  returnToScanFailed:
    'Impossible de dÃ©connecter le produit. RÃ©essayez avant de revenir au scan.',
  openProductPage: 'Ouvrir la page produit',
  refresh: 'Actualiser les informations',
  loading: 'Chargement en cours…',
  readonlyNotice: 'Réglages affichés depuis le produit.',
  commandsUnavailable:
    'Les commandes seront disponibles dans un prochain lot.',
  lockModeControls: {
    title: 'Condamnation',
    executing: 'Envoi du mode de condamnation…',
    sent: 'Mode de condamnation envoyé. Lecture de contrôle en cours.',
    failed: 'Échec de l’envoi du mode de condamnation.',
    unavailable: 'Commande de condamnation indisponible',
    lockedOpen: {
      label: 'Maintien ouvert',
    },
    lockedClosed: {
      label: 'Verrouillage fermé',
    },
  },
  userSpeedControls: {
    apply: 'Appliquer',
    current: 'Valeur lue :',
    draft: 'Valeur à appliquer :',
    executing: 'Envoi de la vitesse…',
    sent: 'Vitesse envoyée. Lecture de contrôle en cours.',
    failed: 'Échec de l’envoi de la vitesse.',
    unavailable: 'Commande de vitesse indisponible',
  },
  userTimingControls: {
    apply: 'Appliquer',
    current: 'Valeur lue :',
    draft: 'Valeur à appliquer :',
    executing: 'Envoi de la temporisation…',
    sent: 'Temporisation envoyée. Lecture de contrôle en cours.',
    failed: 'Échec de l’envoi de la temporisation.',
    unavailable: 'Commande de temporisation indisponible',
  },
  userPeripheralControls: {
    executing: 'Envoi du réglage d’éclairage…',
    sent: 'Réglage d’éclairage envoyé. Lecture de contrôle en cours.',
    failed: 'Échec de l’envoi du réglage d’éclairage.',
    unavailable: 'Commande d’éclairage indisponible',
  },
  nameRoomControls: {
    apply: 'Appliquer',
    title: 'Nom et pièce',
    current: 'Valeur lue :',
    draft: 'Valeur à écrire :',
    nameLabel: 'Nom',
    roomLabel: 'Pièce',
    executing: 'Envoi du nom et de la pièce…',
    sent:
      'Nom et pièce envoyés. Une nouvelle recherche peut être nécessaire.',
    failed: 'Échec de l’envoi du nom et de la pièce.',
    unavailable: 'Commande nom/pièce indisponible',
    rooms: {
      bedroom: 'Chambre',
      entrance: 'Entrée',
      livingRoom: 'Salon',
      kitchen: 'Cuisine',
      diningRoom: 'Salle à manger',
      bathroom: 'Salle de bain',
      toilet: 'Toilettes',
      garageUtilityRoom: 'Garage / Buanderie',
      hall: 'Salle',
      playroom: 'Salle de jeux',
    },
    errors: {
      empty: 'Le nom est obligatoire.',
      invalidCharacters:
        'Seuls les lettres, chiffres, espaces et tirets sont autorisés.',
      tooLong: 'Le nom complet est limité à 15 caractères.',
      tooShort: 'Le nom doit contenir au moins 5 caractères.',
      invalidRoom: 'Pièce non reconnue.',
    },
  },
  weightRangeControls: {
    apply: 'Appliquer',
    current: 'Plage lue :',
    draft: 'Plage à appliquer :',
    executing: 'Envoi de la plage de poids…',
    sent: 'Plage de poids envoyée. Lecture de contrôle en cours.',
    failed: 'Échec de l’envoi de la plage de poids.',
    unavailable: 'Commande de plage de poids indisponible',
  },
  deferredSensitiveActions: {
    title: 'Fonctions en attente de validation physique',
    notice:
      'Ces commandes existent dans la référence Phase 1 mais restent désactivées dans la Phase 2 tant que leur comportement n’a pas été validé sur matériel.',
    learning: 'Apprentissage',
    radarTest1: 'Lancer le test radar 1',
    radarTest2: 'Lancer le test radar 2',
    peripheralLock: 'Modifier le verrouillage périphériques',
    disabledReason: 'Validation physique requise',
  },
  professionalPeripheralDiagnostics: {
    title: 'Diagnostic périphériques',
    readonlyNotice:
      'États lus depuis le produit. Aucune commande de test ou de verrouillage n’est envoyée.',
    radarTest1: 'Test radar 1',
    radarTest2: 'Test radar 2',
    peripheralLock: 'Verrouillage périphériques',
    enabled: 'Activé',
    disabled: 'Désactivé',
  },
  professionalInputControls: {
    title: 'Configuration des entrées',
    current: 'Valeur lue :',
    input1: 'Entrée 1',
    input2: 'Entrée 2',
    button: 'Bouton',
    radar: 'Radar',
    executing: 'Envoi de la configuration d’entrée…',
    sent: 'Configuration d’entrée envoyée. Lecture de contrôle en cours.',
    failed: 'Échec de l’envoi de la configuration d’entrée.',
    unavailable: 'Commande de configuration d’entrée indisponible',
  },
  professionalScalarControls: {
    apply: 'Appliquer',
    current: 'Valeur lue :',
    draft: 'Valeur à appliquer :',
    executing: 'Envoi du paramètre professionnel…',
    sent: 'Paramètre professionnel envoyé. Lecture de contrôle en cours.',
    failed: 'Échec de l’envoi du paramètre professionnel.',
    unavailable: 'Commande de paramètre professionnel indisponible',
  },
  professionalAccess: {
    title: 'Accès professionnel',
    message: 'Saisissez le code professionnel pour afficher ces réglages.',
    placeholder: 'Code professionnel',
    cancel: 'Annuler',
    confirm: 'Valider',
    unlock: 'Déverrouiller les réglages professionnels',
    locked: 'Certains réglages professionnels sont masqués.',
    unlocked: 'Réglages professionnels déverrouillés.',
    failed: 'Code professionnel incorrect.',
  },
  productDateActions: {
    setupLabel: 'Mise en service effectuée',
    maintenanceLabel: 'Maintenance effectuée',
    confirmTitle: 'Confirmation requise',
    passwordPlaceholder: 'Mot de passe maintenance',
    cancel: 'Décliner',
    confirm: 'Confirmer',
    awaitingConfirmation: 'Confirmation maintenance requise.',
    executing: 'Envoi de l’action historique…',
    setupSent:
      'Mise en service envoyée. Lecture de contrôle en cours.',
    maintenanceSent:
      'Maintenance envoyée. Lecture de contrôle en cours.',
    setupSentReloadFailed:
      'Mise en service envoyée, mais la lecture de contrôle a échoué.',
    maintenanceSentReloadFailed:
      'Maintenance envoyée, mais la lecture de contrôle a échoué.',
    failed: 'Échec de l’envoi de l’action historique.',
    partialFailed:
      'Maintenance envoyée, mais la mise en service n’a pas été envoyée. ' +
      'Lecture de contrôle en cours.',
    partialReloadFailed:
      'Maintenance envoyée, mais la mise en service n’a pas été envoyée. ' +
      'La lecture de contrôle a échoué.',
    unavailable: 'Action historique indisponible',
    wrongCode: 'Code maintenance incorrect.',
    cancelled: 'Action annulée.',
    setupConfirmation: (date: string) =>
      'Confirmez-vous qu’une mise en service a été effectuée le ' +
      `${date} ? La maintenance sera enregistrée puis la date de mise en ` +
      'service sera définitivement enregistrée si le produit la déclare ' +
      'encore non initialisée.',
    maintenanceConfirmation: (date: string) =>
      'Confirmez-vous qu’une maintenance a été effectuée le ' +
      `${date} ? Le compteur de cycles depuis la dernière maintenance peut ` +
      'être réinitialisé par le firmware.',
  },
  openCommand: {
    cancel: 'Annuler',
    awaitingConfirmation: 'Confirmation requise',
    sent: 'Commande envoyée',
    executing: 'Commande en cours…',
    unavailable: 'Commande indisponible',
    disconnected: 'Périphérique déconnecté',
    stale: 'Résultat obsolète',
    failed: 'Échec de la commande',
    alreadyInProgress: 'Une commande est déjà en cours',
    cancelled: 'Commande annulée',
  },
  widoorCommands: {
    warning:
      'Un mouvement réel du moteur sera déclenché après confirmation.',
    physicalValidationRequired: 'Validation physique requise',
    protected: 'Fonction protégée — validation dédiée requise',
    timedCyclePending:
      'Le cycle temporisé complet reste à valider physiquement.',
    open: {
      label: 'Ouvrir',
      confirmTitle: 'Ouvrir la porte ?',
      confirmMessage:
        'Cette action déclenche un mouvement réel du moteur. Vérifiez que ' +
        'la zone est dégagée et que l’arrêt physique est accessible.',
      confirmAction: 'Ouvrir',
      confirmed: 'Ouverture confirmée',
      notConfirmed: 'Commande envoyée, mais ouverture non confirmée',
    },
    close: {
      label: 'Fermer',
      confirmTitle: 'Fermer la porte ?',
      confirmMessage:
        'Cette action déclenche un mouvement réel du moteur. Vérifiez que ' +
        'la zone est dégagée et que l’arrêt physique est accessible.',
      confirmAction: 'Fermer',
      confirmed: 'Fermeture confirmée',
      notConfirmed: 'Commande envoyée, mais fermeture non confirmée',
    },
    openShortTimed: {
      label: 'Ouverture temporisée courte',
      confirmTitle: 'Lancer l’ouverture temporisée courte ?',
      confirmMessage:
        'Cette action déclenche un mouvement réel du moteur. Vérifiez que ' +
        'la zone est dégagée et que l’arrêt physique est accessible. Le ' +
        'démarrage du mouvement sera contrôlé, mais le cycle temporisé ' +
        'complet devra être validé séparément.',
      confirmAction: 'Lancer',
      confirmed: 'Début d’ouverture temporisée courte confirmé',
      notConfirmed: 'Commande envoyée, mais démarrage non confirmé',
    },
    openLongTimed: {
      label: 'Ouverture temporisée longue',
      confirmTitle: 'Lancer l’ouverture temporisée longue ?',
      confirmMessage:
        'Cette action déclenche un mouvement réel du moteur. Vérifiez que ' +
        'la zone est dégagée et que l’arrêt physique est accessible. Le ' +
        'démarrage du mouvement sera contrôlé, mais le cycle temporisé ' +
        'complet devra être validé séparément.',
      confirmAction: 'Lancer',
      confirmed: 'Début d’ouverture temporisée longue confirmé',
      notConfirmed: 'Commande envoyée, mais démarrage non confirmé',
    },
    learning: {
      label: 'Apprentissage',
      confirmTitle: '',
      confirmMessage: '',
      confirmAction: '',
      confirmed: '',
      notConfirmed: '',
    },
  },
  commandHistory: {
    title: 'Historique des commandes',
    empty: 'Aucune commande terminée pendant cette session.',
    duration: 'Délai',
    confirmation: 'Confirmation moteur',
    timedCycle: 'Cycle temporisé',
    statuses: {
      confirmed: 'Confirmée',
      timeout: 'Non confirmée',
      failed: 'Échec',
      disconnected: 'Déconnectée',
      stale: 'Obsolète',
      unavailable: 'Indisponible',
      cancelled: 'Annulée',
    },
    confirmations: {
      confirmed: 'Confirmée',
      timeout: 'Non confirmée',
      unavailable: 'Indisponible',
      notRequired: 'Non requise',
      notValidated: 'Non validée',
      none: 'Aucune',
    },
    timedCycles: {
      notObserved: 'Non observé',
      pendingPhysicalValidation: 'Validation physique en attente',
      validated: 'Validé',
      failed: 'Échec',
    },
  },
  sections: {
    commands: 'Commandes',
    settings: 'Réglages',
    information: 'Informations',
    userSettings: 'Réglages utilisateur',
    professionalSettings: 'Réglages professionnels',
    identity: 'Produit connecté',
    version: 'Versions et identification',
    dates: 'Dates et cycles',
    maintenance: 'Maintenance',
    motorState: 'État moteur',
  },
  states: {
    available: 'Disponible',
    unavailable: 'Non disponible',
    invalid: 'Donnée invalide',
    notLoaded: 'Non chargée',
    failed: 'Lecture impossible',
    disconnected: 'Déconnecté',
    stale: 'Données obsolètes',
    connected: 'Connecté',
    invalidProfile: 'Profil incohérent',
    partialSuccess: 'Succès partiel',
    success: 'Informations disponibles',
    cancelled: 'Lecture annulée',
  },
  profile: 'Profil',
  productName: 'Nom produit',
  displayedName: 'Nom affiché',
  room: 'Pièce',
  deviceId: 'Identifiant du périphérique',
  connection: 'Connexion',
  lastRefresh: 'Dernière actualisation',
  noRoom: 'Non renseignée',
  noValue: 'Non disponible',
  noMotorState: 'Aucun état moteur reçu',
  yes: 'Oui',
  no: 'Non',
  notInitialized: 'Non initialisée',
  invalidHistoricalDate: 'Date historique invalide',
  historicalFad: 'FAD historique brut',
  historicalFadNotice: 'Signification métier non confirmée',
  rawFrame: 'Trame brute',
  technicalDetails: 'Détails techniques',
  serviceUuid: 'Service UUID',
  characteristicUuid: 'Caractéristique UUID',
  errorCode: 'Code d’erreur',
  errors: {
    serviceAbsent: 'Service BLE non disponible',
    characteristicAbsent: 'Non disponible sur ce firmware',
    notReadable: 'Lecture non prise en charge',
    unknown: 'Une erreur est survenue pendant la lecture.',
  },
  errorDetails: {
    serviceAbsent:
      'Le service BLE nécessaire n’est pas exposé par ce produit.',
    characteristicAbsent:
      'La caractéristique BLE nécessaire n’est pas exposée par ce produit.',
    notReadable:
      'La caractéristique BLE ne permet pas la lecture sur ce produit.',
  },
  version: {
    motor: 'Logiciel moteur',
    ble: 'Logiciel Bluetooth',
    stack: 'Stack BLE',
    productType: 'Type produit brut',
    productSubtype: 'Sous-type',
    crc: 'CRC',
    motorAddress: 'Adresse moteur',
  },
  dates: {
    firstCommissioning: 'Première mise en service',
    lastMaintenance: 'Dernière maintenance',
    totalCycles: 'Total cycles',
    cyclesSinceMaintenance: 'Cycles depuis maintenance',
  },
  maintenance: {
    initializationCount: 'Initialisations',
    cyclesSinceInitialization: 'Cycles depuis initialisation',
    obstacleDetectionCount: 'Détections obstacle',
    wrongStopOpenCount: 'Mauvais arrêts ouverture',
    wrongStopCloseCount: 'Mauvais arrêts fermeture',
    learningCycleCount: 'Cycles d’apprentissage',
    encoderErrorCount: 'Erreurs encodeur',
    motorErrorCount: 'Erreurs moteur',
  },
  user: {
    lockMode: 'Mode de condamnation',
    lockModeRaw: 'Mode de condamnation brut',
    openSpeed: 'Vitesse d’ouverture',
    closeSpeed: 'Vitesse de fermeture',
    shortTiming: 'Temporisation courte',
    longTiming: 'Temporisation longue',
    staticLight: 'Éclairage statique',
    dynamicLight: 'Éclairage dynamique',
    rgb: 'Indicateur RGB',
    peripheralByte1: 'Octet périphériques utilisateur 1',
    peripheralByte2: 'Octet périphériques utilisateur 2',
  },
  professional: {
    weightRange: 'Plage de poids',
    exactWeight: 'Poids exact',
    breakForceAtOpen: 'Force/freinage à l’ouverture',
    nearOpenSpeed: 'Vitesse de fin d’ouverture',
    nearCloseSpeed: 'Vitesse de fin de fermeture',
    nearOpenTorque: 'Couple fin ouverture',
    nearCloseTorque: 'Couple fin fermeture',
    brakingOpenPower: 'Freinage ouverture',
    obstacleSensitivity: 'Sensibilité obstacle',
    nearOpenProportional: 'Proportionnelle ouverture',
    nearCloseProportional: 'Proportionnelle fermeture',
    nearOpenIntegral: 'Intégrale ouverture',
    nearCloseIntegral: 'Intégrale fermeture',
    peripherals:
      'Périphériques bruts (entrées, verrou et tests radar)',
    peripheralsWithoutLock:
      'Périphériques bruts (entrées et tests radar)',
  },
  motor: {
    rawState: 'État brut',
    stateLabel: 'État technique',
    currentPosition: 'Position courante',
    maximumPosition: 'Position maximale',
    percentage: 'Ouverture',
    error: 'Erreur',
    switchesRaw: 'Bits d’état bruts',
    pushAndGo: 'Push & Go',
    ble: 'BLE',
    automaticManual: 'Auto/Manuel',
    direction: 'Direction',
    pairing: 'Appairage',
    openingStarted: 'Début ouverture',
    stoppedAfterOpening: 'Arrêt après ouverture',
    closingStarted: 'Début fermeture',
    stoppedAfterClosing: 'Arrêt après fermeture',
    unknown: 'État non documenté',
  },
} as const;
