// Catalogue local destiné à être remplacé par le futur système i18n.
export const SCAN_PRODUCT_READ_TEXT = {
  title: 'Lecture des informations produit',
  diagnosticNotice:
    'Diagnostic brut en lecture seule destiné à la validation de migration.',
  historicalGattTitle: 'Diagnostic caractéristique historique',
  passiveGattNotice:
    'Aucune opération BLE n’est exécutée par ce diagnostic.',
  servicePresent: 'Service présent',
  characteristicPresent: 'Caractéristique présente',
  propertiesAvailable: 'Propriétés fournies par la plateforme',
  readable: 'Lecture',
  writable: 'Écriture avec réponse',
  writableWithoutResponse: 'Écriture sans réponse',
  notifiable: 'Notification',
  indicatable: 'Indication',
  descriptors: 'Descripteurs',
  rawProperties: 'Propriétés brutes',
  unknown: 'Inconnu',
  read: 'Lire les informations',
  cancel: 'Annuler la lecture',
  loading: 'Lectures BLE séquentielles en cours…',
  ready: 'Prêt à lire les informations.',
  unavailable: 'Lecture indisponible.',
  disconnected: 'Périphérique déconnecté.',
  detectionInProgress: 'Identification du produit en cours.',
  scanInProgress: 'Scan BLE en cours.',
  operationInProgress: 'Une opération BLE est déjà en cours.',
  staleContext: 'La connexion a changé.',
  profile: 'Profil',
  deviceId: 'Identifiant du périphérique',
  startedAt: 'Début',
  completedAt: 'Fin',
  globalStatus: 'Statut global',
  successfulReads: 'Lectures réussies',
  invalidReads: 'Trames invalides',
  unavailableReads: 'Lectures indisponibles',
  failedReads: 'Lectures échouées',
  partialSuccess: 'Succès partiel',
  partialSuccessDetails:
    'Certaines lectures ont réussi et d’autres sont indisponibles, invalides ou en échec.',
  yes: 'Oui',
  no: 'Non',
  status: {
    success: 'Succès',
    'partial-success': 'Succès partiel',
    failed: 'Échec',
    disconnected: 'Déconnecté',
    stale: 'Ancienne connexion',
    cancelled: 'Annulé',
    'invalid-frame': 'Trame invalide',
    unavailable: 'Indisponible',
  },
  sections: {
    version: 'Version',
    datesAndCycles: 'Dates et cycles',
    maintenance: 'Maintenance',
    userParameters: 'Paramètres utilisateur',
    advancedParameters: 'Paramètres professionnels',
  },
  serviceUuid: 'Service UUID',
  characteristicUuid: 'Caractéristique UUID',
  rawFrame: 'Trame brute',
  length: 'Longueur',
  bytes: 'octet(s)',
  decodeErrors: 'Erreurs de décodage',
  nativeError: 'Erreur',
  dataUnavailable: 'Données indisponibles',
  invalidFrame: 'La trame reçue est invalide.',
  staleResult: 'Ce résultat appartient à une ancienne connexion et est ignoré.',
  motorAddressUnavailable: 'Indisponible (adresse complète absente)',
  notInitialized: 'Non initialisée',
  invalidDate: 'Date historique invalide',
  historicalFad: 'FAD historique',
  historicalFadMeaning: 'Signification métier non confirmée',
  rawDate: 'Octets bruts',
  hourSuffix: 'h',
  stackVersion: 'Version stack BLE',
  bleSoftwareVersion: 'Version logiciel BLE',
  productType: 'Type produit brut',
  productSubtype: 'Sous-type',
  motorSoftwareVersion: 'Version moteur',
  crc: 'CRC',
  motorAddress: 'Adresse moteur',
  firstCommissioning: 'Première mise en service',
  lastMaintenance: 'Dernière maintenance',
  totalCycles: 'Total cycles',
  cyclesSinceMaintenance: 'Cycles depuis maintenance',
  initializationCount: 'Initialisations',
  cyclesSinceInitialization: 'Cycles depuis initialisation',
  obstacleDetectionCount: 'Détections obstacle',
  wrongStopOpenCount: 'Mauvais arrêts ouverture',
  wrongStopCloseCount: 'Mauvais arrêts fermeture',
  learningCycleCount: 'Cycles d’apprentissage',
  encoderErrorCount: 'Erreurs encodeur',
  motorErrorCount: 'Erreurs moteur',
  lockMode: 'Mode de condamnation',
  lockModeRaw: 'Mode de condamnation brut',
  openSpeed: 'Vitesse ouverture',
  closeSpeed: 'Vitesse fermeture',
  shortOpenTime: 'Temporisation courte',
  longOpenTime: 'Temporisation longue',
  peripheralBytes: 'Octets périphériques bruts',
  peripheralFlags: 'Bits périphériques confirmés',
  peripheralFlagLabels: {
    dynamicLight: 'Éclairage dynamique',
    staticLight: 'Éclairage statique',
    input1Radar: 'Entrée 1 radar',
    input2Radar: 'Entrée 2 radar',
    rgbIndicator: 'Indicateur RGB',
  },
  weightRange: 'Bornes de poids',
  exactWeight: 'Poids exact',
  breakForceAtOpen: 'Force/freinage à l’ouverture',
  nearOpenSpeed: 'Vitesse de fin ouverture',
  nearCloseSpeed: 'Vitesse de fin fermeture',
  nearOpenTorque: 'Couple de fin ouverture',
  nearCloseTorque: 'Couple de fin fermeture',
  brakingOpenPower: 'Freinage ouverture',
  obstacleSensitivity: 'Sensibilité obstacle',
  nearOpenProportional: 'Proportionnelle ouverture',
  nearCloseProportional: 'Proportionnelle fermeture',
  nearOpenIntegral: 'Intégrale ouverture',
  nearCloseIntegral: 'Intégrale fermeture',
} as const;
