import {
  defineProductProfile,
  ProductProfileDefinition,
} from '../product-profile.types';

export const WIDOOR_PRODUCT_PROFILE = defineProductProfile({
  profile: 'widoor',
  family: 'widoor',
  variant: 'standard',
  route: '/product/widoor',
  productName: 'WIDOOR',
  maximumWeightLabel: null,
  weightRanges: [],
  userFields: [
    'open-speed',
    'close-speed',
    'short-timing',
    'rgb',
  ],
  professionalFields: [
    'break-force-at-open',
    'near-open-speed',
    'near-close-speed',
    'near-open-torque',
    'near-close-torque',
    'near-open-proportional',
    'near-close-proportional',
    'near-open-integral',
    'near-close-integral',
    'peripherals',
  ],
  visibleLockModes: [],
  hiddenMotorSwitches: ['push-and-go'],
  openSpeedRange: { min: 25, max: 100 },
  closeSpeedRange: { min: 35, max: 100 },
  nearOpenSpeedRange: { min: 70, max: 100 },
  nearCloseSpeedRange: { min: 50, max: 100 },
  lockMinimumMotorVersionExclusive: [1, 0, 0],
  commands: [
    'motor-open',
    'motor-close',
    'motor-open-short-timed',
  ],
  sensitiveActions: [
    'learning',
    'radar-test-1',
    'radar-test-2',
    'professional-peripheral-lock',
    'reset',
  ],
  capabilities: {
    demo: true,
    professionalInputs: true,
    professionalAccessFields: [],
    weightRangeControl: 'none',
  },
  behavior: {
    immediateWritePolicy: 'widoor',
    sliderAutoWrite: true,
    advancedSettingsConfirmation: false,
    showControlsBeforeRead: true,
    refreshAfterMaintenanceAction: true,
  },
  information: {
    showMotorAddress: false,
    showMaintenanceDates: false,
    showCurrentWeightRange: false,
    supplementalMaintenanceFields: [
      'initializations',
      'cycles-since-init',
      'obstacles',
      'encoder-errors',
      'motor-errors',
    ],
  },
  ui: {
    widoorLayout: true,
    widoorSliderInteraction: true,
  },
} satisfies ProductProfileDefinition);
